name: Create Documentation PDFs
on: push
#  schedule:
 #   - cron: 0 6 * * *

jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ksnifte/actions-makepdfs@master
      if: github.ref == 'refs/heads/master'
    - uses: actions/upload-artifact@v1
      with:
        name: platform-architecture-docs
        path: tmp
    - uses: actions/download-artifact@v1
      with:
        name: platform-architecture-docs
        path: tmp
